# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools
build:
  tools:
    python: "3.10"

# Build documentation in the source/ directory with Sphinx
sphinx:
   configuration: source/conf.py

# Build formats apart from html
formats:
  - pdf

# Python details
python:
  install:
    - requirements: doc/requirements.txt
  system_packages: true
